openapi: '3.0.3'
info:
  title: BagdexAPI
  version: '1.0'
servers:
  - url: https://bagdexapi.vercel.app/api
tags:
  - name: API
    description: Informações básicas da API.
  - name: Tipos
    description: Informações sobre as tipagens dos Bagmon.
  - name: Dex
    description: Informações sobre os Bagmon.
  - name: Níveis de Extinção
    description: Informações sobre os níveis de extinção dos Bagmon.
paths:
  /status:
    get:
      tags:
        - API
      summary: Veja o status atual da API
      description: Veja o status atual da API.
      operationId: status
      responses:
        '200':
          description: API executando normalmente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Nome da API
                    example: BagdexAPI
                  status:
                    type: string
                    description: Status da API
                    example: OK
                  version:
                    type: string
                    description: Versão da API
                    example: 1.0.0
  /types:
    get:
      tags:
        - Tipos
      summary: Veja os tipos dos Bagmon
      description: Veja tipos de Bagmon de acordo com os parâmetros fornecidos.
      operationId: types
      parameters:
        - name: id
          in: query
          description: O Id de uma tipagem específica.
          required: false
          explode: true
          schema:
            type: integer
            example: 1
        - name: weaknesses
          in: query
          description: Fraquezas, separadas por vírgula, que podem corresponder a um ou mais tipos.
          required: false
          explode: true
          schema:
            type: string
            example: 7,12
      responses:
        '200':
          description: Foi encontrada uma tipagem correspondente ao Id fornecido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Id da tipagem
                    format: int64
                    example: 1
                  name:
                    type: string
                    description: Nome da tipagem
                    example: aquático
                  weaknesses:
                    type: array
                    description: Fraquezas da tipagem
                    example: [ 7, 12, 18 ]
                  artwork:
                    type: string
                    description: URL da arte da tipagem
                    example: null
        '404':
          description: Nenhum tipo correspondeu aos parâmetros fornecidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Identificador do erro
                    example: ERR_TYPE_NOT_FOUND
                  message:
                    type: string
                    description: Mensagem de erro
                    example: The provided 'id' does not match any type.
  /dex:
    get:
      tags:
        - Dex
      summary: Veja a lista de Bagmon
      description: Veja a lista de Bagmon correspondentes aos parâmetros fornecidos.
      operationId: dex
      parameters:
        - name: id
          in: query
          description: O Id do Bagmon.
          required: false
          explode: true
          schema:
            type: integer
            example: 1
        - name: starter
          in: query
          description: Apenas Bagmon iniciais (true); apenas os que não são iniciais (false).
          required: false
          explode: true
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: Foi encontrado um Bagmon correspondente ao Id fornecido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: O Id do Bagmon
                    format: int64
                    example: 1
                  name:
                    type: string
                    description: O nome do Bagmon
                    example: Voara
                  types:
                    type: array
                    description: Tipagens do Bagmon
                    example: [ 13 ]
                  artwork:
                    type: string
                    description: URL da arte do Bagmon
                    example: null
                  pre-evolution:
                    type: integer
                    description: Id da pré-evolução do Bagmon
                    example: null
                  evolution:
                    type: object
                    properties:
                      level:
                        type: integer
                        description: Nível que o Bagmon atual evoluirá
                        example: 16
                      to:
                        type: integer
                        description: Id do Bagmon para qual o atual será evoluído
                        example: 2
                  abilities:
                    type: array
                    description: Habilidades que o Bagmon pode possuir
                    example: []
                  starter:
                    type: boolean
                    description: Declara se o Bagmon atual é um inicial
                    example: true
                  extinction-level:
                    type: integer
                    description: Nível de extinção que o Bagmon se encontra
                    example: null
        '404':
          description: Nenhum Bagmon correspondeu aos parâmetros fornecidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Identificador do erro
                    example: ERR_BAGMON_NOT_FOUND
                  message:
                    type: string
                    description: Mensagem de erro
                    example: The provided 'id' does not match any Bagmon.
  /extinction-levels:
    get:
      tags:
        - Níveis de Extinção
      summary: Veja os níveis de extinção dos Bagmon
      description: Veja os níveis de extinção dos Bagmon de acordo com os parâmetros fornecidos.
      operationId: extinction-levels
      parameters:
        - name: level
          in: query
          description: O nível de extinção.
          required: false
          explode: true
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: Foi encontrado um nível de extinção correspondente ao fornecido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  level:
                    type: integer
                    description: O nível de extinção
                    example: 0
                  description:
                    type: string
                    description: A descrição do nível de extinção
                    example: Pouco Preocupante
        '404':
          description: Nenhum nível de extinção correspondeu aos parâmetros fornecidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Identificador do erro
                    example: ERR_EXTINCTION_LEVEL_INVALID
                  message:
                    type: string
                    description: Mensagem de erro
                    example: The provided 'level' does not match any extinction level.